### ISSUE TITLE
First param path could not be empty string

### ISSUE THREAD

**Issue by AndreLion** [Secbone/koa-static2#4]
The first param `path` has to be assigned some value, if it is an empty string, the static server always returns 404.

**Comment by Secbone** [comment]
@AndreLion the first param should be a no-empty string that using for filter which path should be served. empty string means no path should serve.

**Comment by AndreLion** [comment]
In my scenario, I want the static server to serve the root of my application. so what is the correct value of `path` in this case?

**Comment by Secbone** [comment]
@AndreLion  I think it's a dangerous thing to serve the root folder and suggest you to use a special  folder to serve static files had better. :)

**Comment by AndreLion** [comment]
make sense , thanks
